//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakePromoDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public Ingredients()
        {
            this.Cakes = new HashSet<Cake>();
        }
    
        public int IngredientsId { get; set; }
        public string UserId { get; set; }
        public string TimeStamp { get; set; }
    
        public virtual ICollection<Cake> Cakes { get; set; }
    }
}
